In [1]:
import pandas as pd

df = pd.DataFrame({
    'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Refund': ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Divorced',
                       'Married', 'Divorced', 'Single', 'Married', 'Single'],
    'Taxable Income': [125, 100, 70, 120, 95, 60, 220, 85, 75, 90],
    'Cheat': ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
})

df

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

In [2]:
df.head()

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes

In [4]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
4    5     No       Divorced              95   Yes
7    8     No         Single              85   Yes
8    9     No        Married              75    No

In [6]:
df.iloc[3:7]

   Tid Refund Marital Status  Taxable Income Cheat
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No

In [8]:
df.iloc[4:8,2:4]

  Marital Status  Taxable Income
4       Divorced              95
5        Married              60
6       Divorced             220
7         Single              85

In [9]:
df.iloc[:, 1:4]

  Refund Marital Status  Taxable Income
0    Yes         Single             125
1     No        Married             100
2     No         Single              70
3    Yes        Married             120
4     No       Divorced              95
5     No        Married              60
6    Yes       Divorced             220
7     No         Single              85
8     No        Married              75
9     No         Single              90

In [11]:
df_2 = pd.read_csv('Iris.csv')

In [12]:
df_2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df_2 = df.d