In [3]:
import pandas as pd

df = pd.DataFrame({
    'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Refund': ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Divorced',
                       'Married', 'Divorced', 'Single', 'Married', 'Single'],
    'Taxable Income': [125, 100, 70, 120, 95, 60, 220, 85, 75, 90],
    'Cheat': ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
})

df

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

In [4]:
df.head()

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes

In [5]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital Status  Taxable Income Cheat
0    1    Yes         Single             125    No
4    5     No       Divorced              95   Yes
7    8     No         Single              85   Yes
8    9     No        Married              75    No

In [6]:
df.iloc[3:7]

   Tid Refund Marital Status  Taxable Income Cheat
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No

In [7]:
df.iloc[4:8,2:4]

  Marital Status  Taxable Income
4       Divorced              95
5        Married              60
6       Divorced             220
7         Single              85

In [8]:
df.iloc[:, 1:4]

  Refund Marital Status  Taxable Income
0    Yes         Single             125
1     No        Married             100
2     No         Single              70
3    Yes        Married             120
4     No       Divorced              95
5     No        Married              60
6    Yes       Divorced             220
7     No         Single              85
8     No        Married              75
9     No         Single              90

In [9]:
df_2 = pd.read_csv('Iris.csv')

In [10]:
df_2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
df_2 = df_2.drop(3, axis=0)                  # delete 4th row

In [12]:
df_2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [13]:
df_2 = df_2.drop(columns=df_2.columns[3])

In [14]:
df_2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
4   5            5.0           3.6           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

In [15]:
import pandas as pd

df = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01',
                     '2021-02-10', '2010-11-25'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Bonus': [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
})



print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [16]:
df.to_csv('employees.csv', index=False)

In [17]:
df.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [18]:
df.shape

(5, 10)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

In [20]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [21]:
df.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [22]:
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [23]:
df['Salary'].mean()

np.float64(60000.0)

In [24]:
df['Bonus'].sum()

np.int64(27500)

In [25]:
df['Age'].min()

np.int64(28)

In [26]:
df['Rating'].max()

np.float64(4.7)

In [27]:
df.sort_values(by='Salary', ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [28]:
df['Performance'] = pd.cut(
    df['Rating'],
    bins=[0 ,4.0, 4.5, 5],
    labels=['Average', 'Good', 'Excellent'],
    right=False
)

In [29]:
df['Performance']

0    Excellent
1         Good
2      Average
3    Excellent
4      Average
Name: Performance, dtype: category
Categories (3, str): ['Average' < 'Good' < 'Excellent']

In [30]:
# import numpy as np

# df['Performance'] = np.select(
#     [
#         df['Rating'] >= 4.5,
#         df['Rating'] >= 4.0
#     ],
#     [
#         'Excellent',
#         'Good'
#     ],
#     default='Average'
# )

# print(df)
# from chatgpt new meathod

In [31]:
print(df.isnull().sum())

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [32]:
df = df.rename(columns={'Employee_ID': 'ID'})

In [33]:
df.head()

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [34]:
df['Years_of_Experience']

0     4
1     8
2    10
3     3
4    12
Name: Years_of_Experience, dtype: int64

In [35]:
df[df['Department'] == 'IT']

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [36]:
df['Tax'] = df['Salary'] * 0.10

In [37]:
df.head()

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [38]:
df.shape

(5, 12)

In [39]:
df.describe()

,ID,Age,Salary,Years_of_Experience,Bonus,Rating,Tax
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000,6000.000000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975,790.569415
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000,5000.000000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000,5500.000000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000,6000.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000,6500.000000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000,7000.000000

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
 10  Performance          5 non-null      category
 11  Tax                  5 non-null      float64
dtypes: category(1), float64(2), int64(5), str(4)
memory usage: 709.0 bytes